# Generated by Django 4.0.4 on 2022-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='numbers_of_pages',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
