# Generated by Django 4.0.4 on 2022-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_description_book_numbers_of_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
